dist: xenial
language: python
sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=registry.iconicto.com/rathumakara-discord-bot
before_install:
  - sudo snap install kubectl --classic
  - sudo snap install doctl
  - sudo snap connect doctl:kube-config
  - doctl k8s cluster kubeconfig save $DIGITALOCEAN_CLUSTER -t $DIGITALOCEAN_TOKEN
  - doctl auth init -t $DIGITALOCEAN_TOKEN
  - echo $DOCKER_PASSWORD | docker login registry.iconicto.com -u $DOCKER_USERNAME --password-stdin

script:
  - docker build -f Deployment/Production/Dockerfile -t $IMAGE_NAME .
  - docker tag $IMAGE_NAME $IMAGE_NAME:commit-$TRAVIS_COMMIT
  - docker tag $IMAGE_NAME $IMAGE_NAME:production
  - docker push $IMAGE_NAME

deploy:
  provider: script
  script: kubectl set image deployment $DEPLOYMENT_NAME rathumakara-discord-bot=$IMAGE_NAME:commit-$TRAVIS_COMMIT
  on:
    branch: master